name: Teams
version: '${project.version}'
main: org.mbf.teams.Teams
api-version: '1.20'
commands:
  test:
    description: Test command
    usage: /<command> [sub_args] <material> <amount>
  team:
    description: Team command
    usage: /<command> [args]
    aliases: [t]